name: FateOfDice release

on:
    release:
        types: [created]

jobs:
  generate-windows:
    name: Add windows executables to releas
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
    - name: Build with pyinstaller
      run: pyinstaller ./FateOfDice.spec
    - name: Zip build
      run: zip --junk-paths dist/Windows_executables.zip dist/*
    - name: Upload build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/Windows_executables.zip
        asset_name: Windows_executables.zip
        tag: ${{ github.ref }}
        overwrite: true
