name: FateOfDice release

on:
    release:
        types: [created]

jobs:
  generate-windows:
    name: Add windows executables to release
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        pip install pyinstaller
    - name: Build with pyinstaller
      run: pyinstaller ./FateOfDice.spec
    - name: Zip build
      run: |
        mkdir tmp/FateOfDice
        cp dist/* tmp/FateOfDice
        cd tmp
        7z a -tzip FateOfDiceWindowsBinary.zip FateOfDice/*
    - name: Upload build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: tmp/FateOfDiceWindowsBinary.zip
        asset_name: FateOfDiceWindowsBinary.zip
        tag: ${{ github.ref }}
        overwrite: true
