name: FateOfDice release

on:
    release:
        types: [created]

jobs:
  generate-windows:
    name: Build windows executables with PyInstaller
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/windows/FateOfDice.exe
        asset_name: FateOfDice.exe
        tag: ${{ github.ref }}
        overwrite: true

  generate-linux:
    name: Build linux executables with PyInstaller
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .
      - uses: actions/upload-artifact@v2
        with:
          name: FateOfDice
          path: dist/linux
